### PR TITLE
Fix the MySQL backend for the current schema

### PR DESCRIPTION
**Pull request by hectoras**
backend_mysql_load_data:
- Import coverart tables in a similar fashion to what we currently do with statistics tables.

backend_mysql_update_schema_from_file:
- Support CREATE TABLE queries that don't end with "\n);"
- Basic support for Postgres POINT fields (dummy mapping to VARCHAR(100))
- Map Postgres TIMESTAMPTZ datatype to MySQL TIMESTAMP.
- [Debug] Print what column is currently being added
- Ugly hack for ignoring CONSTRAINTs on CREATE TABLE that span multiple lines (checking if second word is "OR"/"IS"/"=", or if parsing yield a bracket as a field name).

I think the following issues can be closed, either because this this pull request fixes them, or because they were previously fixed but left open:
- https://github.com/elliotchance/mbzdb/issues/59 - Another schema issue: release group cover art
- https://github.com/elliotchance/mbzdb/issues/49 - MusicBrainz Schema seems to have changed (statistic tables)
- https://github.com/elliotchance/mbzdb/issues/43 - "Install/Update database schematic" table creation error. (problems with the enum types, this was already closed).
- https://github.com/elliotchance/mbzdb/issues/39 - init.pl option "create index" failed (now when a UNIQUE index creation fails, we retry with a non-UNIQUE index).
- https://github.com/elliotchance/mbzdb/issues/38 - load_data also tries to load data from directories (a patch was already merged).

[Review on Reviewable](https://reviewable.io/reviews/elliotchance/mbzdb/67)

### CODE REVIEW

**Comment by kiranjoseph** [comment]
This PR saved my day. I had been struggling to get the '(' on the same line working by tweeking around mbs-server sql scripts. This PR solved it in a jiffy.

**Comment by elliotchance** [comment]
Sorry about this very old pull request, should it still be reviewed to go in?

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/elliotchance/mbzdb/67#-:-KAIVMT9D8l9HFbFv0Mm:2064391959)*

**Comment by hectoras** [comment]
I think it should. 

Note this pull request also adds some additional features besides fixing de table creation error:
- Allowing "batch" operation from the command line (allowing to select the option to run directly from the command line with no user input).
- An option to only decompress the dumps but not to load them
- A command line switch to select the bzip decompressor to use
- An option to decompress all files in parallel using fork() (so, on multicore systems, you can create the tables from one process and run one additional process per .tar.bz2 file at the same time).
- An option to use pbzip2 (or another decompressor) to unzip the dumps (BTW the bz2 files' format from the MusicBrainz FTP are not suited (yet?) for parallel operation).
- Downloading and executing the CreateSlaveIndexes.sql file, so medium and track tables are usable again.

Keep in mind these changes have been tested only on MySQL/MariaDB. I've been using the procedure described on the README file from my fork for some time with no issues.

**Comment by elliotchance** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[init.pl, line 19 \[r1\]](https://reviewable.io:443/reviews/elliotchance/mbzdb/67#-KASLC-Y17gPMxaFbT8A:-KASLC-Y17gPMxaFbT8B:-412906630) ([raw file](https://github.com/elliotchance/mbzdb/blob/c90ab37bf4f89903ade8ed50b87c21f988c2a227/init.pl#L19)):*
Is there a `null` in perl? My perl is very rusty...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/elliotchance/mbzdb/67)*

**Comment by hectoras** [comment]
Changed "null" with "undef": https://github.com/hangar18cc/mbzdb/commit/4ef06efab3ce0a737fe5a9f389fa8148c7361b67

**Comment by elliotchance** [comment]
Thanks for all your work keeping this up to date. I will try to be more responsive with PRs in the future :)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/elliotchance/mbzdb/67#-:-KAWvnxQcTPqoOpN1jte:1817320715)*

**Comment by elliotchance** [comment]
https://github.com/elliotchance/mbzdb/releases/tag/v7.0

**Pull request merged**
